### ISSUE TITLE
没有payment的方法

### ISSUE THREAD

**Issue by Rockroc** [NeverRetrun/kuaishou-mini-app#1]
我看文档写着支付payment，但是代码并没找到这个方法

**Comment by crynocri** [comment]
可以尝试这样调用。 可以参考 `tests/Payment/WeChatTest.php`里面的方法

```php
$app = new KuaiShouMiniApp(
    new Config(
        'appId',
        'appSecret'
    )
);

$app->payment()->wechat( 一些参数 );
```

**Comment by Rockroc** [comment]
![image](https://user-images.githubusercontent.com/8446061/152948732-f65d5a4e-fbe9-4bb1-8798-d5752702de03.png)

并没有这个文件

**Comment by Rockroc** [comment]
composer require cvoid/kuaishou-mini-app  这种方式安装的缺少了payment模块

**Comment by crynocri** [comment]
@Rockroc 

之前0.0.1版本没有包含Payment

我新打了一个tag。 0.0.2版本是最新的包含Payment了。

**Comment by Rockroc** [comment]
我看了下payment的方法，并没有调用到 快手的预下单接口，请问就是得到$result['sign']  然后让我用sign单独去请求预下单接口吗，但提交的参数对比预下单接单还少了个open_id，会影响么

**Comment by crynocri** [comment]
@Rockroc  

因为这个当时我是在去年写的。 当时快手小程序还在初步公测时段。 

我看了下文档 已经和之前完全不一致了。目前是不可用了。

**Comment by Rockroc** [comment]
> @Rockroc
> 
> 因为这个当时我是在去年写的。 当时快手小程序还在初步公测时段。
> 
> 我看了下文档 已经和之前完全不一致了。目前是不可用了。

嗯，好的，那我自己折腾下，非常感谢
